Repository filecoin-project/boost, pull requests merged in 2021-11, with the labels that each got.

#56 ux - publish now
  gql/resolver_dealpublish.go
  gql/schema.graphql
  react/src/DealDetail.js
  react/src/DealPublish.js
  react/src/gql.js
  react/src/index.css
Labels: area/ux

#54 ux: deal publish
  gql/resolver.go
  gql/resolver_dealpublish.go
  gql/schema.graphql
  gql/server.go
  node/modules/storageminer.go
  react/src/App.js
  react/src/DealDetail.js
  react/src/DealPublish.js
  react/src/gql.js
  react/src/index.css
  react/src/util.js
  storagemarket/deal_execution.go
  storagemarket/deal_publisher.go
Labels: area/ux

#46 Stub out funds manager logs
  gql/resolver.go
  gql/resolver_dealpublish.go
  gql/resolver_funds.go
  gql/schema.graphql
  gql/server.go
  node/modules/storageminer.go
  react/src/App.js
  react/src/Chart.js
  react/src/DealDetail.js
  react/src/DealPublish.js
  react/src/Funds.js
  react/src/gql.js
  react/src/index.css
  react/src/util.js
  storagemarket/deal_execution.go
  storagemarket/deal_publisher.go
Labels: area/ux, area/funds

#45 add two wallets as required when initialising boost
  README.md
  cmd/boost/init.go
  cmd/devnet/main.go
  node/builder.go
  node/config/types.go
Labels: area/funds

#40 HTTP Pull Transport
  gql/resolver.go
  storagemarket/deal_execution.go
  storagemarket/deal_handler.go
  storagemarket/newdealps.go
  storagemarket/provider.go
  storagemarket/types/deal_state.go
  storagemarket/types/types.go
  transport/httptransport/http_transport.go
  transport/httptransport/http_transport_test.go
  transport/interface.go
  transport/types/types.go
Labels: area/storage, status/in-progress
